apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod 
resources:
- ../../../../../../base/fe

images:
- name: yasminemarzouk/template-fe-prod
  newName: docker.io/yasminemarzouk/template-fe-prod
  newTag: fe-prod

patches:
- path: ./patches/deployment.yaml
  target:
    group: apps
    kind: Deployment
    version: v1