apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyconverter-production
  namespace: argocd
spec:
  project: default
  source:
<<<<<<< HEAD
    repoURL: 'https://github.com/Yasminemaroukk/appTest.git'
=======
    repoURL: 'hhttps://github.com/Yasminemaroukk/appTest.git'
>>>>>>> origin/main
    targetRevision: HEAD
    path: k8s/overlays/production
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
