apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anime
  namespace: dev   # Change the namespace to 'prod'
spec:
  project: default
  source:
    repoURL: https://github.com/Yasminemaroukk/kustomize-.git
    targetRevision: HEAD
    path: k8s/overlays/development
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true 
