apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

resources:
  - be-deployment.yaml
  - be-service.yaml

commonLabels:
  app.kubernetes.io/name: backend
  app.kubernetes.io/component: backend
