apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- path: fe-deployment-patch.yaml
  target:
    kind: Deployment
    name: fe-template
images:
- name: yasminemarzouk/template-fe
  newName: docker.io/yasminemarzouk/template-fe
  newTag: b78cbae
