apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: fe-template
    
   
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: be-template
    
   

images:
- name: yasminemarzouk/template-fe-prod
  newName: docker.io/yasminemarzouk/template-fe-prod
  newTag: 8fa94ed95ca54d0480ebcff91147285cb2160e5b
- name: yasminemarzouk/template-be_prod
  newName: docker.io/yasminemarzouk/template-be-prod
  newTag: 689d916
