resources:
- ../../base

patches:
- path: be-deployment-prod-patch.yaml
  target:
    kind: Deployment
    name: be-template
images:
- name: yasminemarzouk/template-fe
  newName: docker.io/yasminemarzouk/template-fe
  newTag: d00d17d
