resources:
- ../../base

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: be-template
images:
- name: yasminemarzouk/template-fe
  newName: docker.io/yasminemarzouk/template-fe
  newTag: f671287
