resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: fe-template
   
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: be-template
   

images:
- name: yasminemarzouk/template-fe
  newName: docker.io/yasminemarzouk/template-fe
  newTag: 92adc14
- name: yasminemarzouk/template-be
  newName: docker.io/yasminemarzouk/template-be
  newTag: fe12385
