apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: fe-template
   
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: be-template
   

images:
- name: yasminemarzouk/template-fe-dev
  newName: docker.io/yasminemarzouk/template-fe-dev
  newTag: 8b81d7a4a860a780d76a3cadb06def240b7b85e6
- name: yasminemarzouk/template-fe-dev
  newName: docker.io/yasminemarzouk/template-be-dev
  newTag: 8b81d7a4a860a780d76a3cadb06def240b7b85e6

