resources:
- ../../base
patches:
- path: fe-deployment-patch.yaml
  target:
    kind: Deployment
    name: fe-template
    version: v1

images:
- name: yasminemarzouk/template-fe
  newName: docker.io/yasminemarzouk/template-fe
  newTag: 92adc14
