apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: fe-template
   
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: be-template
   

images:
- name: yasminemarzouk/template-fe-dev
  newName: docker.io/yasminemarzouk/template-fe-dev
  newTag: f89355a0ff3122a9b64930d70021100625fe2cfc
- name: yasminemarzouk/template-fe-dev
  newName: docker.io/yasminemarzouk/template-be-dev
  newTag: f89355a0ff3122a9b64930d70021100625fe2cfc

