apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: fe-template
   
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: be-template
   

images:
- name: yasminemarzouk/template-fe-dev
  newName: docker.io/yasminemarzouk/template-fe-dev
  newTag: 4dab788b95247851ca555bb82de1c67316af14f4
- name: yasminemarzouk/template-fe-dev
  newName: docker.io/yasminemarzouk/template-be-dev
  newTag: 4dab788b95247851ca555bb82de1c67316af14f4

