apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev 
resources:
- ../../../../../../base/backend-deployment.yaml/

images:
- name: yasminemarzouk/template-fe-dev
  newName: docker.io/yasminemarzouk/template-be-dev
  newTag: b4addc2b6af9f91c873baaabcbb5fa6bb7a8e3d2

patches:
- path: ./patches/deployment.yaml
  target:
    group: apps
    kind: Deployment
    version: v1