apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stag
resources:
- ../../../../../../base/be
- ./overlays/pod-disruption-budget.yaml
images:
- name: yasminemarzouk/template-be  
  newName: yasminemarzouk/temp-be-stag 
  newTag: be-stag  
patches:
- path: ./patches/deployment.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
configMapGenerator:
- envs:
  - ./generators/config.properties
  name: myconfigmap
secretGenerator:
- envs:
  - ./generators/secret.properties
  name: mysecret

