apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod 
resources:
- ../../../../../../base/be

images:
- name: yasminemarzouk/template-be-prod
  newName: docker.io/yasminemarzouk/template-be-prod
  newTag: be-prod

patches:
- path: ./patches/deployment.yaml
  target:
    group: apps
    kind: Deployment
    version: v1